app/models.py
from datetime import datetime
from app import db, login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash


@login_manager.user_loader
def load_user(id):
    return User.query.get(int(id))

class User(db.Model, UserMixin):
    """
    User model for the application.
    """
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(20), nullable=False)
    last_name = db.Column(db.String(20), nullable=False)
    user_name = db.Column(db.String(20), nullable=False)
    image = db.Column(db.String(20), nullable=False, default='default.jpg')
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(60), nullable=False)

    def set_password(self, password):
        """
        Hash the password using generate_password_hash.
        """
        self.password = generate_password_hash(password)

    def check_password(self, password):
        """
        Check the hashed password using check_password_hash.
        """
        return check_password_hash(self.password, password)

    def __repr__(self):
        return f"User('{self.user_name}', '{self.email}')"


class Vehicle(db.Model):
    """
    Vehicle model for the application.
    """
    id = db.Column(db.Integer, primary_key=True)
    license_plate = db.Column(db.String(20), nullable=False)
    make = db.Column(db.String(50), nullable=True)
    model = db.Column(db.String(50), nullable=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return f"Vehicle('{self.license_plate}', '{self.make}', '{self.model}')"

class ParkingSpot(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    location = db.Column(db.String(100))
    spot_number = db.Column(db.String(10))
    is_available = db.Column(db.Boolean, default=True)
    image = db.Column(db.String(100))  # URL or path to the image of the parking spot
    bookings = db.relationship('Booking', backref='spot', lazy='dynamic')

    def __repr__(self):
        return f"ParkingSpot('{self.location}', '{self.spot_number}', Available: {self.is_available})"

class Booking(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.Date, index=True)
    start_time = db.Column(db.DateTime, index=True)
    end_time = db.Column(db.DateTime, index=True)
    status = db.Column(db.String(20))  # 'confirmed', 'cancelled', 'completed'
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    spot_id = db.Column(db.Integer, db.ForeignKey('parking_spot.id'))
    vehicle_id = db.Column(db.Integer, db.ForeignKey('vehicle.id'))

    def __repr__(self):
        return f"Booking('{self.date}', '{self.start_time}', '{self.end_time}', Status: {self.status})"

app/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, Length, EqualTo, ValidationError
from app.models import User


class RegistrationForm(FlaskForm):
    first_name = StringField('First Name', validators=[DataRequired(), Length(min=2, max=20)])
    last_name = StringField('Last Name', validators=[DataRequired(), Length(min=2, max=20)])
    user_name = StringField('Username',validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=6, max=20)])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), Length(min=6, max=20), EqualTo('password')])
    submit = SubmitField('Sign Up')

    def validate_username(self, user_name):
        user = User.query.filter_by(username=user_name.data).first()
        if user:
            raise ValidationError('That username is already taken. Please choose a different one.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('That email is already in use. Please choose a different one.')



class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=6, max=20)])
    submit = SubmitField('Login')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

from app.config import Config

db = SQLAlchemy()
login_manager = LoginManager()
login_manager.login_view = 'users.login'
login_manager.login_message_category = 'info'

def create_app():
    app = Flask(__name__)

    app.config.from_object(Config)

    db.init_app(app)
    login_manager.init_app(app)

    from app.main.routes import main
    from app.users.routes import users

    app.register_blueprint(main)
    app.register_blueprint(users)

    # Initialize the database
    with app.app_context():
        db.create_all()


    return app

app/main/routes.py
from flask import Blueprint, render_template, request, url_for, flash, redirect

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home():
    return render_template('home.html')

app/users/routes.py
from flask import Blueprint, render_template, request, url_for, flash, redirect
from flask_login import current_user, login_user

from app import db
from app.models import User
from app.users.forms import RegistrationForm, LoginForm

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            user_name=form.user_name.data,
            email=form.email.data
        )
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        flash('Thank you for registering. You can now log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.check_password(form.password.data):
            login_user(user)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
    return render_template('login.html', form=form)

app/templates/home.html
{% extends 'layout.html' %}
{% block title %}Park{% endblock %}

{% block body %}
    <h2>Welcome to the parking App</h2>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css"
              rel="stylesheet"
              integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr"
              crossorigin="anonymous"
        />
        <link rel="stylesheet"
              href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
        <link rel="stylesheet" href="{{ url_for('static', filename="styles.css") }}" />
        <title>{% block title %}Park{% endblock %}</title>
    </head>
    <body>
        <nav class="navbar fixed-top navbar-expand-lg bg-body-tertiary bg-dark border-bottom border-body" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ url_for('main.home') }}">Kyle's</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                          <a class="nav-link active" aria-current="page" href="{{ url_for('main.home') }}">Home</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link disabled" aria-disabled="true" href="#">Bookings</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link disabled" aria-disabled="true" href="#">Account</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="align-center mt-5">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
        </div>

        {% block body %}
        {% endblock %}
    </body>
    <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"
    ></script>
    <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.min.js"
            integrity="sha384-7qAoOXltbVP82dhxHAUje59V5r2YsVfBafyUDxEdApLPmcdhBPg1DKg1ERo0BZlK"
            crossorigin="anonymous"
    ></script>
</html>

app/templates/login.html
{% extends 'layout.html' %}
    {% block title %}Login{% endblock %}

    {% block body %}
        <section class="vh-100" style="background-color: #1f2024;">
            <div class="container py-5 h-100">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col col-xl-10">
                        <div class="card" style="border-radius: 1rem;">
                            <div class="row g-0">
                                <div class="col-md-6 col-lg-5 d-none d-md-block">
                                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/img1.webp"
                                alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem;" />
                                </div>
                                <div class="col-md-6 col-lg-7 d-flex align-items-center">
                                    <div class="card-body p-4 p-lg-5 text-black">

                                        <form method="post" action="">
                                            {{ form.csrf_token }}
                                            <div class="d-flex align-items-center mb-3 pb-1">
                                                <i class="fas fa-cubes fa-2x me-3" style="color: #ff6219;"></i>
                                                <span class="h1 fw-bold mb-0">Kyle's Parking Space</span>
                                            </div>

                                            <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Login into your account</h5>

                                            <!-- Email input -->
                                            <div class="form-floating mb-4">
                                                {% if form.email.errors %}
                                                    {{ form.email(class="form-control is-invalid", id="email", placeholder="Email") }}
                                                    <div class="invalid-feedback">
                                                        {% for error in form.email.errors %}
                                                            <span>{{ error }}</span>
                                                        {% endfor %}
                                                    </div>
                                                {% else %}
                                                    {{ form.email(class="form-control", id="email", placeholder="Email") }}
                                                {% endif %}
                                                <label for="email">Email</label>
                                            </div>

                                            <!-- Password input -->
                                            <div class="form-floating mb-4">
                                                {% if form.password.errors %}
                                                    {{ form.password(class="form-control is-invalid", id="pwd", placeholder="Password") }}
                                                    <div class="invalid-feedback">
                                                        {% for error in form.password.errors %}
                                                            <span>{{ error }}</span>
                                                        {% endfor %}
                                                    </div>
                                                {% else %}
                                                    {{ form.password(class="form-control", id="pwd", placeholder="Password") }}
                                                {% endif %}
                                                <label for="pwd">Password</label>
                                            </div>

                                            <div class="pt-1 mb-4">
                                                <button data-mdb-button-init data-mdb-ripple-init class="btn btn-dark btn-lg btn-block" type="submit">Login</button>
                                            </div>

                                            <a class="small text-muted" href="#!">Forgot password?</a>
                                            <p class="mb-5 pb-lg-2" style="color: #393f81;">Don't have an account?
                                                <a href="{{ url_for('users.register') }}" style="color: #393f81;">Register here</a></p>
                                            <a href="#!" class="small text-muted">Terms of use.</a>
                                            <a href="#!" class="small text-muted">Privacy policy</a>
                                        </form>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    {% endblock %}

app/templates/register.html
{% extends 'layout.html' %}
    {% block title %}Register{% endblock %}

    {% block body %}
        <!-- Section: Design Block -->
        <section class="text-center text-lg-start">
              <style>
                .cascading-right {
                  margin-right: -50px;
                }

                @media (max-width: 991.98px) {
                  .cascading-right {
                    margin-right: 0;
                  }
                }
              </style>

            <!-- Jumbotron -->
            <div class="container py-4">
                <div class="row g-0 align-items-center">
                    <div class="col-lg-6 mb-5 mb-lg-0 mx-auto">
                        <div class="card cascading-right bg-body-tertiary" style="
                    backdrop-filter: blur(30px);
                    ">
                        <div class="card-body p-5 shadow-5 text-center">
                            <h2 class="fw-bold mb-5">Sign up now</h2>
                            <form method="post" action="">
                                {{ form.csrf_token }}
                                <!-- 2 column grid layout with text inputs for the first and last names -->
                                <div class="row">
                                    <div class="col-md-6 mb-4">
                                        <div class="form-floating mb-4">
                                            {% if form.first_name.errors %}
                                                {{ form.first_name(class="form-control is-invalid", id="first_name", placeholder="First name") }}
                                                <div class="invalid-feedback">
                                                    {% for error in form.first_name.errors %}
                                                        <span>{{ error }}</span>
                                                    {% endfor %}
                                                </div>
                                            {% else %}
                                                {{ form.first_name(class="form-control", id="first_name", placeholder="First name") }}
                                            {% endif %}
                                            <label for="first_name">First name</label>
                                        </div>
                                    </div>
                                    <div class="col-md-6 mb-4">
                                        <div class="form-floating mb-4">
                                            {% if form.last_name.errors %}
                                                {{ form.last_name(class="form-control is-invalid", id="last_name", placeholder="Last name") }}
                                                <div class="invalid-feedback">
                                                    {% for error in form.last_name.errors %}
                                                        <span>{{ error }}</span>
                                                    {% endfor %}
                                                </div>
                                            {% else %}
                                                {{ form.last_name(class="form-control", id="last_name", placeholder="Last name") }}
                                            {% endif %}
                                            <label for="last_name">Last name</label>
                                        </div>
                                    </div>
                                </div>
                                <!-- Username input -->
                                <div class="row">
                                    <div class="col-md-6 mb-4">
                                        <div class="form-floating mb-4">
                                            {% if form.user_name.errors %}
                                                {{ form.user_name(class="form-control is-invalid", id="user_name", placeholder="Username") }}
                                                <div class="invalid-feedback">
                                                    {% for error in form.user_name.errors %}
                                                        <span>{{ error }}</span>
                                                    {% endfor %}
                                                </div>
                                            {% else %}
                                                {{ form.user_name(class="form-control", id="user_name", placeholder="Username") }}
                                            {% endif %}
                                            <label for="user_name">Username</label>
                                        </div>
                                    </div>
                                    <div class="col-md-6 mb-4">
                                        <!-- Email input -->
                                        <div class="form-floating mb-4">
                                            {% if form.email.errors %}
                                                {{ form.email(class="form-control is-invalid", id="email", placeholder="Email") }}
                                                <div class="invalid-feedback">
                                                    {% for error in form.email.errors %}
                                                        <span>{{ error }}</span>
                                                    {% endfor %}
                                                </div>
                                            {% else %}
                                                {{ form.email(class="form-control", id="email", placeholder="Email") }}
                                            {% endif %}
                                            <label for="email">Email</label>
                                        </div>
                                    </div>
                                </div>

                                <!-- Password input -->
                                <div class="form-floating mb-4">
                                    {% if form.password.errors %}
                                        {{ form.password(class="form-control is-invalid", id="pwd", placeholder="Password") }}
                                        <div class="invalid-feedback">
                                            {% for error in form.password.errors %}
                                                <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    {% else %}
                                        {{ form.password(class="form-control", id="pwd", placeholder="Password") }}
                                    {% endif %}
                                    <label for="pwd">Password</label>
                                </div>
                                <!-- Confirm Password input -->
                                <div class="form-floating mb-4">
                                    {% if form.confirm_password.errors %}
                                        {{ form.confirm_password(class="form-control is-invalid", id="confirm_password", placeholder="Confirm Password") }}
                                        <div class="invalid-feedback">
                                            {% for error in form.confirm_password.errors %}
                                                <span>{{ error }}</span>
                                            {% endfor %}
                                        </div>
                                    {% else %}
                                        {{ form.confirm_password(class="form-control", id="confirm_password", placeholder="Confirm Password") }}
                                    {% endif %}
                                    <label for="confirm_password">Confirm Password</label>
                                </div>


                                <!-- Submit button -->
                                    <button type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-block mb-4">
                                        Sign Up
                                    </button>

                              <!-- Register buttons -->
                                <div class="text-center">
                                    <p>or sign up with:</p>
                                    <button  type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1">
                                        <i class="fab fa-facebook-f"></i>
                                    </button>

                                    <button  type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1">
                                        <i class="fab fa-google"></i>
                                    </button>

                                    <button  type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1">
                                        <i class="fab fa-twitter"></i>
                                    </button>

                                    <button  type="button" data-mdb-button-init data-mdb-ripple-init class="btn btn-link btn-floating mx-1">
                                        <i class="fab fa-github"></i>
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

                    <div class="col-lg-6 mb-5 mb-lg-0">
                        <img src="https://mdbootstrap.com/img/new/ecommerce/vertical/004.jpg" class="w-100 rounded-4 shadow-4"
                  alt="" />
                    </div>
                </div>
            </div>

        </section>

    {% endblock %}